### ISSUE TITLE
How do I add dragome-gdx-bullet in gradle.build?

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-html5-tools#26]
I can not find example to use bullet extension in gdx-shadertoy

https://github.com/xpenatan/gdx-shadertoy/search?utf8=✓&q=bullet

I see here https://github.com/xpenatan/gdx-dragome-backend/tree/master/extensions/gdx-bullet/gdx-bullet-dragome that it is separate maven project.

Can you deploy it to https://github.com/xpenatan/mvn-repo/tree/master/snapshots/com/badlogicgames/gdx
and write example how config gradle for build project with gdx bullet extension in desctop and web?

**Comment by xpenatan** [comment]
Not possible now. only eclipse and having dragome projects source imported
