### ISSUE TITLE
getDisplayMode() returns null

### ISSUE THREAD

**Issue by fxzjshm** [xpenatan/gdx-html5-tools#38]
In this file [DragomeGraphics.java](https://github.com/xpenatan/gdx-dragome-backend/blob/master/backends/gdx-backend-dragome/src/com/badlogic/gdx/backends/dragome/DragomeGraphics.java), `getDisplayMode()` returns null.
This causes some codes to fail, for example I got a `TypeError` (and I cannot catch it). I think this method should return the size of the `<canvas>`.
Moreover, other functions should return what it should return instead of `null`.
Thank you for fixing them.

**Comment by xpenatan** [comment]
I've added this method. If there is any other method you need I'll try to port from gwt or create it if its possible.

**Comment by fxzjshm** [comment]
OK, thank you very much! I'll test it later this week.
