### ISSUE TITLE
Has development stopped?

### ISSUE THREAD

**Issue by EtK2000** [xpenatan/gdx-html5-tools#39]

**Comment by xpenatan** [comment]
Hi, yes. Since there is still bugs in dragome and did not have any single commit to keep it better I paused.

**Comment by xpenatan** [comment]
Hi @EtK2000. Development have been restored.  Some big refactoring will be made.  This repo will host dragome, gwt and teavm libs.  The reason for this is that I plan to create teavm backend that will reuse some dragome code (backend, bullet, freetype, etc) . 

With a single repo will be easier to maintain and share/reuse web code for all three platforms (gwt, dragome and teavm).

My first step is to fix and finish all gdx dragome stuff to gradle. My DragomeSDK fork is already converted to gradle and have snapshots ready.

**Comment by EtK2000** [comment]
Yay!
That's awesome to hear.
I'd be willing to help with a bit if needed.
