### ISSUE TITLE
Compiler problems | 3 ERRORS

### ISSUE THREAD

**Issue by aallnneess** [xpenatan/gdx-html5-tools#51]
Hey,

ive got 3 Compiler problems:

```
#################################################################
| ERROR[0]
| Class: -
| Method: com.artemis.utils.reflect.ClassReflection.getDeclaredField(Ljava/lang/Class;Ljava/lang/String;)Lcom/artemis/utils/reflect/Field;
| Text: Class java.lang.NoSuchFieldException was not found
| 
| ----
| 
| ERROR[1]
| Class: com/badlogic/gdx/math/Octree.java:285
| Method: com.badlogic.gdx.math.Octree$OctreeNode.query(Lcom/badlogic/gdx/math/Frustum;Lcom/badlogic/gdx/utils/ObjectSet;)V
| Text: Method com.badlogic.gdx.math.Intersector.intersectFrustumBounds(Lcom/badlogic/gdx/math/Frustum;Lcom/badlogic/gdx/math/collision/BoundingBox;)Z was not found
| 
| ----
| 
| ERROR[2]
| Class: com/artemis/link/MutatorUtil.java:10
| Method: com.artemis.link.MutatorUtil.getGeneratedMutator(Lcom/artemis/link/LinkSite;)Ljava/lang/Object;
| Text: Method java.lang.Class.getDeclaredClasses()[Ljava/lang/Class; was not found

#################################################################


```

This is my Buildclass:
```

public class HyperLap2DTest {

    public static void main(String[] args) {
        URL appJarAppUrl = null;
        try {
            appJarAppUrl = new File("c:/GitHub/gdx-html5-tools/everrun1.jar").toURI().toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        TeaBuildConfiguration teaBuildConfiguration = new TeaBuildConfiguration();
        teaBuildConfiguration.assetsPath.add(new File("c:/GitHub/new liftoff/assets"));
        teaBuildConfiguration.webappPath = new File("c:/GitHub/gdx-html5-tools").getAbsolutePath();
        teaBuildConfiguration.obfuscate = false;
        teaBuildConfiguration.mainApplicationClass = "com.tutorial.artemisTestlab.GameMain";
        teaBuildConfiguration.additionalClasspath.add(appJarAppUrl);

        teaBuildConfiguration.reflectionInclude.add("games.rednblack.editor.renderer");
        teaBuildConfiguration.reflectionInclude.add("games.rednblack.h2d.extension.spine");
        teaBuildConfiguration.reflectionInclude.add("games.rednblack.h2d.extension.talos");
        teaBuildConfiguration.reflectionInclude.add("com.tutorial.artemisTestlab.components");
        teaBuildConfiguration.reflectionInclude.add("com.tutorial.artemisTestlab.systems");
        teaBuildConfiguration.reflectionInclude.add("com.tutorial.artemisTestlab.Scripts");
        teaBuildConfiguration.reflectionInclude.add("com.ray3k.stripe.scenecomposer");

        teaBuildConfiguration.reflectionInclude.add("com.artemis");
        teaBuildConfiguration.reflectionInclude.add("com.talosvfx.talos.runtime");

        teaBuildConfiguration.reflectionExclude.add("com.artemis.annotation");
        teaBuildConfiguration.reflectionExclude.add("com.artemis.utils.reflect");

        TeaBuilder.build(teaBuildConfiguration);
    }
}
```

Libgdx Game works in lwjgl3/Android/Gwt.

There was a big hyperlap update to beta, maybe something else needs to be configured...

**Edit:** Link to web-app: 
http://45.133.9.32:8080/everrunTeavm270122/

thanks so far

**Comment by xpenatan** [comment]
> Hey,
> 
> ive got 3 Compiler problems:
> 
> ```
> #################################################################
> | ERROR[0]
> | Class: -
> | Method: com.artemis.utils.reflect.ClassReflection.getDeclaredField(Ljava/lang/Class;Ljava/lang/String;)Lcom/artemis/utils/reflect/Field;
> | Text: Class java.lang.NoSuchFieldException was not found
> | 
> | ----
> | 
> | ERROR[1]
> | Class: com/badlogic/gdx/math/Octree.java:285
> | Method: com.badlogic.gdx.math.Octree$OctreeNode.query(Lcom/badlogic/gdx/math/Frustum;Lcom/badlogic/gdx/utils/ObjectSet;)V
> | Text: Method com.badlogic.gdx.math.Intersector.intersectFrustumBounds(Lcom/badlogic/gdx/math/Frustum;Lcom/badlogic/gdx/math/collision/BoundingBox;)Z was not found
> | 
> | ----
> | 
> | ERROR[2]
> | Class: com/artemis/link/MutatorUtil.java:10
> | Method: com.artemis.link.MutatorUtil.getGeneratedMutator(Lcom/artemis/link/LinkSite;)Ljava/lang/Object;
> | Text: Method java.lang.Class.getDeclaredClasses()[Ljava/lang/Class; was not found
> 
> #################################################################


ERROR[0]
For NoSuchFieldException I'll have to investigate if I'll need to emulate it or it should obtain the class from java core. It does not exist in https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/lang/

ERROR[1]
I think that method don't exist in libgdx 1.10.0. I guess you need to use snapshots
https://github.com/libgdx/libgdx/blob/gdx-parent-1.10.0/gdx/src/com/badlogic/gdx/math/Intersector.java

ERROR[2]
teavm class emulation is called TClass and 'getDeclaredClasse's method don't exist =/.  I guess we need to implement it.
https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/lang/TClass.java
